return {}
-- project one of:
-- {
-- 		"ahmedkhalf/project.nvim",
-- 		config = function()
-- 			require("project_nvim").setup()
-- 			require("telescope").load_extension("projects")
-- 			-- require'telescope'.extensions.projects.projects{}
-- 		end,
-- 	},
-- {
-- 	"coffebar/neovim-project",

-- 	opts = {
-- 		projects = { -- define project roots
-- 			"~/repo/*",
-- 			"~/.config/*",
-- 		},
-- 	},
-- 	init = function()
-- 		-- enable saving the state of plugins in the session
-- 		vim.opt.sessionoptions:append("globals") -- save global variables that start with an uppercase letter and contain at least one lowercase letter.
-- 	end,
-- 	dependencies = {
-- 		{ "nvim-lua/plenary.nvim" },
-- 		{ "nvim-telescope/telescope.nvim", tag = "0.1.4" },
-- 		{ "Shatur/neovim-session-manager" },
-- 	},
-- 	lazy = false,
-- 	priority = 100,
-- },
-- {
-- "ahmedkhalf/project.nvim",
-- }
